### PR TITLE
Update API version, improvements in API controller.

### PR DESCRIPTION
**Pull request by kegor**
Replicated changes from https://github.com/groupdocs-total/GroupDocs.Total-for-NET-MVC/pull/81.

### CODE REVIEW

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity decreasing per file
==============================
+ src/Products/Editor/Controllers/EditorApiController.cs  -17
         

Clones removed
==============
+ src/Products/Editor/Controllers/EditorApiController.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-total/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5118802&bid=16830366)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/Products/Editor/Controllers/EditorApiController.cs  -17
         

Clones removed
==============
+ src/Products/Editor/Controllers/EditorApiController.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5118828&bid=16830465)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/Products/Editor/Controllers/EditorApiController.cs  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5118828&bid=16830465)

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity decreasing per file
==============================
+ src/Products/Editor/Controllers/EditorApiController.cs  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-total/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5118802&bid=16830366)

**Pull request merged**
