### PR TITLE
Update Signature API version.

### PR DESCRIPTION
**Pull request by kegor**
Replicated changes from https://github.com/groupdocs-signature/GroupDocs.Signature-for-.NET-MVC/pull/32.

### CODE REVIEW

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 16
           

Clones added
============
- src/Products/Signature/Controllers/SignatureApiController.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-total/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5327085&bid=17434946)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Clones added
============
- src/Products/Signature/Controllers/SignatureApiController.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5327084&bid=17434945)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Clones added
============
- src/Products/Signature/Controllers/SignatureApiController.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5327084&bid=17434945)

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 16
           

Clones added
============
- src/Products/Signature/Controllers/SignatureApiController.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-total/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5327085&bid=17434946)

**Pull request merged**
