### PR TITLE
[WIP] Update Annotation/Signature configuration and code refactoring for using zoom feature.

### PR DESCRIPTION
**Pull request by kegor**
Replicated changes from: https://github.com/groupdocs-total/GroupDocs.Total-for-NET-MVC/pull/94.

### CODE REVIEW

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 36
           

Clones added
============
- src/Products/Signature/Controllers/SignatureApiController.cs  1
         

Clones removed
==============
+ src/Products/Annotation/Controllers/AnnotationApiController.cs  -3
+ src/Products/Signature/Loader/SignatureLoader.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5698126&bid=18652795)

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 39
           

Clones added
============
- src/Products/Signature/Controllers/SignatureApiController.cs  1
         

Clones removed
==============
+ src/Products/Signature/Loader/SignatureLoader.cs  -2
+ src/Products/Annotation/Controllers/AnnotationApiController.cs  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-total/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5698127&bid=18652796)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 36
           

Clones added
============
- src/Products/Signature/Controllers/SignatureApiController.cs  1
         

Clones removed
==============
+ src/Products/Signature/Loader/SignatureLoader.cs  -2
+ src/Products/Annotation/Controllers/AnnotationApiController.cs  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5698126&bid=18652795)

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 39
           

Clones added
============
- src/Products/Signature/Controllers/SignatureApiController.cs  1
         

Clones removed
==============
+ src/Products/Signature/Loader/SignatureLoader.cs  -2
+ src/Products/Annotation/Controllers/AnnotationApiController.cs  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-total/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5698127&bid=18652796)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 36
           

Clones added
============
- src/Products/Signature/Controllers/SignatureApiController.cs  1
         

Clones removed
==============
+ src/Products/Signature/Loader/SignatureLoader.cs  -2
+ src/Products/Annotation/Controllers/AnnotationApiController.cs  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5698126&bid=18652795)

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 39
           

Clones added
============
- src/Products/Signature/Controllers/SignatureApiController.cs  1
         

Clones removed
==============
+ src/Products/Signature/Loader/SignatureLoader.cs  -2
+ src/Products/Annotation/Controllers/AnnotationApiController.cs  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-total/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5698127&bid=18652796)

**Pull request merged**
