### PR TITLE
Updating Сomparison API version and related code changes.

### PR DESCRIPTION
**Pull request by kegor**
Replicated changes from https://github.com/groupdocs-total/GroupDocs.Total-for-NET-MVC/pull/96.

### CODE REVIEW

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 14
           

Complexity increasing per file
==============================
- src/Products/Comparison/Service/ComparisonServiceImpl.cs  2
         

Clones added
============
- src/Products/Comparison/Controllers/ComparisonApiController.cs  1
- src/Products/Comparison/Config/ComparisonConfiguration.cs  1
         

Clones removed
==============
+ src/Products/Comparison/Service/ComparisonServiceImpl.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-total/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5799053&bid=18981352)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 10
           

Complexity increasing per file
==============================
- src/Products/Comparison/Service/ComparisonServiceImpl.cs  2
         

Clones added
============
- src/Products/Comparison/Controllers/ComparisonApiController.cs  1
- src/Products/Comparison/Config/ComparisonConfiguration.cs  1
         

Clones removed
==============
+ src/Products/Comparison/Service/ComparisonServiceImpl.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5799052&bid=18981350)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
           

Complexity increasing per file
==============================
- src/Products/Comparison/Service/ComparisonServiceImpl.cs  2
         

Clones added
============
- src/Products/Comparison/Config/ComparisonConfiguration.cs  1
         

Clones removed
==============
+ src/Products/Comparison/Service/ComparisonServiceImpl.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5799052&bid=18981350)

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
           

Complexity increasing per file
==============================
- src/Products/Comparison/Service/ComparisonServiceImpl.cs  2
         

Clones added
============
- src/Products/Comparison/Config/ComparisonConfiguration.cs  1
         

Clones removed
==============
+ src/Products/Comparison/Service/ComparisonServiceImpl.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-total/GroupDocs.Total-for-NET-WebForms/pullRequest?prid=5799053&bid=18981352)

**Review by Pavel-Teplitsky — APPROVED** [review]

**Pull request merged**
